### ISSUE TITLE
Cosmetic fixes

### ISSUE THREAD

**Issue by RaoOfPhysics** [OpenCosmics/opencosmics.github.io#2]
- ~~Change header to "Cosmic Rays" instead of "Cosmic-Ray Physics"~~
- "Visit Our Blog" button is broken on smaller screens. HALP!

**Comment by tanahy** [comment]
Where is said button? I could use some CSS magic.

**Comment by RaoOfPhysics** [comment]
@tanah: Woo! I was just about to ping you in the Gitter room about this. :D

The `master` branch contains all the backend stuff for http://opencosmics.github.io

**Comment by RaoOfPhysics** [comment]
(I also really need to update that landing page. It was made as a temporary thing a year ago, but now that the project is moving forward, the page needs some love.)

**Comment by tanahy** [comment]
Ok, I'm on it. And indeed, the lorem lipsums are always a embarrassing thing ;).

**Comment by RaoOfPhysics** [comment]
@tanah: Especially if you're fluent in Latin and every other word is a swearword. ;) (Not really…)
